import { defineConfig } from 'vitepress'

const sidebars = {
  '/': [
    {
      text: 'Architecture',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/architecture/overview' },
        { text: 'Box Lifecycle', link: '/architecture/lifecycle' },
        { text: 'Adapter Interfaces', link: '/architecture/adapters' },
        { text: 'Service Registry', link: '/architecture/service-registry' },
        { text: 'Router & Rules', link: '/architecture/router' },
        { text: 'Connection Manager', link: '/architecture/connection' },
        { text: 'Network Manager', link: '/architecture/network' },
        { text: 'Dialer System', link: '/architecture/dialer' },
        { text: 'Listener System', link: '/architecture/listener' },
        { text: 'Sniffing', link: '/architecture/sniffing' },
      ],
    },
    {
      text: 'Proxy Protocols',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/protocols/overview' },
        { text: 'VLESS', link: '/protocols/vless' },
        { text: 'VMess', link: '/protocols/vmess' },
        { text: 'Trojan', link: '/protocols/trojan' },
        { text: 'Shadowsocks', link: '/protocols/shadowsocks' },
        { text: 'ShadowTLS', link: '/protocols/shadowtls' },
        { text: 'Hysteria2', link: '/protocols/hysteria2' },
        { text: 'TUIC', link: '/protocols/tuic' },
        { text: 'AnyTLS', link: '/protocols/anytls' },
        { text: 'NaiveProxy', link: '/protocols/naive' },
        { text: 'WireGuard', link: '/protocols/wireguard' },
        { text: 'SOCKS / HTTP / Mixed', link: '/protocols/socks-http' },
        { text: 'Direct / Block / DNS', link: '/protocols/direct-block-dns' },
        { text: 'Redirect / TProxy', link: '/protocols/redirect-tproxy' },
        { text: 'TUN', link: '/protocols/tun' },
        { text: 'Outbound Groups', link: '/protocols/groups' },
        { text: 'SSH / Tor / Tailscale', link: '/protocols/ssh-tor-tailscale' },
      ],
    },
    {
      text: 'Transport Layer',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/transport/overview' },
        { text: 'V2Ray Transports', link: '/transport/v2ray' },
        { text: 'WebSocket', link: '/transport/websocket' },
        { text: 'gRPC', link: '/transport/grpc' },
        { text: 'HTTP / HTTPUpgrade', link: '/transport/http' },
        { text: 'QUIC', link: '/transport/quic' },
        { text: 'TLS / uTLS / REALITY', link: '/transport/tls' },
        { text: 'kTLS', link: '/transport/ktls' },
        { text: 'Multiplex (smux)', link: '/transport/mux' },
        { text: 'UDP over TCP', link: '/transport/uot' },
        { text: 'TLS Fragmentation', link: '/transport/tls-fragment' },
      ],
    },
    {
      text: 'DNS System',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/dns/overview' },
        { text: 'Client & Router', link: '/dns/client-router' },
        { text: 'Transport Types', link: '/dns/transports' },
        { text: 'FakeIP', link: '/dns/fakeip' },
        { text: 'Hosts & Local', link: '/dns/hosts-local' },
        { text: 'Caching & EDNS0', link: '/dns/caching' },
      ],
    },
    {
      text: 'Advanced Features',
      collapsed: false,
      items: [
        { text: 'Rule Sets (SRS)', link: '/advanced/rule-sets' },
        { text: 'GeoIP / GeoSite', link: '/advanced/geo' },
        { text: 'Process Matching', link: '/advanced/process' },
        { text: 'Clash API', link: '/advanced/clash-api' },
        { text: 'V2Ray API', link: '/advanced/v2ray-api' },
        { text: 'Cache File', link: '/advanced/cache' },
        { text: 'Platform / libbox', link: '/advanced/platform' },
      ],
    },
    {
      text: 'Configuration',
      collapsed: false,
      items: [
        { text: 'Config Structure', link: '/config/structure' },
        { text: 'Option Types', link: '/config/types' },
        { text: 'Build Tags', link: '/config/build-tags' },
      ],
    },
    {
      text: 'Implementation',
      collapsed: false,
      items: [
        { text: 'Checklist', link: '/implementation/checklist' },
        { text: 'Compatibility Notes', link: '/implementation/compatibility' },
      ],
    },
  ],
  '/zh-CN/': [
    {
      text: '架构',
      collapsed: false,
      items: [
        { text: '概述', link: '/zh-CN/architecture/overview' },
        { text: 'Box 生命周期', link: '/zh-CN/architecture/lifecycle' },
        { text: '适配器接口', link: '/zh-CN/architecture/adapters' },
        { text: '服务注册', link: '/zh-CN/architecture/service-registry' },
        { text: '路由与规则', link: '/zh-CN/architecture/router' },
        { text: '连接管理器', link: '/zh-CN/architecture/connection' },
        { text: '网络管理器', link: '/zh-CN/architecture/network' },
        { text: '拨号器系统', link: '/zh-CN/architecture/dialer' },
        { text: '监听器系统', link: '/zh-CN/architecture/listener' },
        { text: '协议嗅探', link: '/zh-CN/architecture/sniffing' },
      ],
    },
    {
      text: '代理协议',
      collapsed: false,
      items: [
        { text: '概述', link: '/zh-CN/protocols/overview' },
        { text: 'VLESS', link: '/zh-CN/protocols/vless' },
        { text: 'VMess', link: '/zh-CN/protocols/vmess' },
        { text: 'Trojan', link: '/zh-CN/protocols/trojan' },
        { text: 'Shadowsocks', link: '/zh-CN/protocols/shadowsocks' },
        { text: 'ShadowTLS', link: '/zh-CN/protocols/shadowtls' },
        { text: 'Hysteria2', link: '/zh-CN/protocols/hysteria2' },
        { text: 'TUIC', link: '/zh-CN/protocols/tuic' },
        { text: 'AnyTLS', link: '/zh-CN/protocols/anytls' },
        { text: 'NaiveProxy', link: '/zh-CN/protocols/naive' },
        { text: 'WireGuard', link: '/zh-CN/protocols/wireguard' },
        { text: 'SOCKS / HTTP / Mixed', link: '/zh-CN/protocols/socks-http' },
        { text: 'Direct / Block / DNS', link: '/zh-CN/protocols/direct-block-dns' },
        { text: 'Redirect / TProxy', link: '/zh-CN/protocols/redirect-tproxy' },
        { text: 'TUN', link: '/zh-CN/protocols/tun' },
        { text: '出站组', link: '/zh-CN/protocols/groups' },
        { text: 'SSH / Tor / Tailscale', link: '/zh-CN/protocols/ssh-tor-tailscale' },
      ],
    },
    {
      text: '传输层',
      collapsed: false,
      items: [
        { text: '概述', link: '/zh-CN/transport/overview' },
        { text: 'V2Ray 传输', link: '/zh-CN/transport/v2ray' },
        { text: 'WebSocket', link: '/zh-CN/transport/websocket' },
        { text: 'gRPC', link: '/zh-CN/transport/grpc' },
        { text: 'HTTP / HTTPUpgrade', link: '/zh-CN/transport/http' },
        { text: 'QUIC', link: '/zh-CN/transport/quic' },
        { text: 'TLS / uTLS / REALITY', link: '/zh-CN/transport/tls' },
        { text: 'kTLS', link: '/zh-CN/transport/ktls' },
        { text: '多路复用 (smux)', link: '/zh-CN/transport/mux' },
        { text: 'UDP over TCP', link: '/zh-CN/transport/uot' },
        { text: 'TLS 分片', link: '/zh-CN/transport/tls-fragment' },
      ],
    },
    {
      text: 'DNS 系统',
      collapsed: false,
      items: [
        { text: '概述', link: '/zh-CN/dns/overview' },
        { text: '客户端与路由', link: '/zh-CN/dns/client-router' },
        { text: '传输类型', link: '/zh-CN/dns/transports' },
        { text: 'FakeIP', link: '/zh-CN/dns/fakeip' },
        { text: 'Hosts 与本地解析', link: '/zh-CN/dns/hosts-local' },
        { text: '缓存与 EDNS0', link: '/zh-CN/dns/caching' },
      ],
    },
    {
      text: '高级功能',
      collapsed: false,
      items: [
        { text: '规则集 (SRS)', link: '/zh-CN/advanced/rule-sets' },
        { text: 'GeoIP / GeoSite', link: '/zh-CN/advanced/geo' },
        { text: '进程匹配', link: '/zh-CN/advanced/process' },
        { text: 'Clash API', link: '/zh-CN/advanced/clash-api' },
        { text: 'V2Ray API', link: '/zh-CN/advanced/v2ray-api' },
        { text: '缓存文件', link: '/zh-CN/advanced/cache' },
        { text: '平台 / libbox', link: '/zh-CN/advanced/platform' },
      ],
    },
    {
      text: '配置',
      collapsed: false,
      items: [
        { text: '配置结构', link: '/zh-CN/config/structure' },
        { text: '选项类型', link: '/zh-CN/config/types' },
        { text: '构建标签', link: '/zh-CN/config/build-tags' },
      ],
    },
    {
      text: '实现',
      collapsed: false,
      items: [
        { text: '检查清单', link: '/zh-CN/implementation/checklist' },
        { text: '兼容性说明', link: '/zh-CN/implementation/compatibility' },
      ],
    },
  ],
  '/ar/': [
    {
      text: 'المعمارية',
      collapsed: false,
      items: [
        { text: 'نظرة عامة', link: '/ar/architecture/overview' },
        { text: 'دورة حياة Box', link: '/ar/architecture/lifecycle' },
        { text: 'واجهات المحولات', link: '/ar/architecture/adapters' },
        { text: 'سجل الخدمات', link: '/ar/architecture/service-registry' },
        { text: 'الموجّه والقواعد', link: '/ar/architecture/router' },
        { text: 'مدير الاتصالات', link: '/ar/architecture/connection' },
        { text: 'مدير الشبكة', link: '/ar/architecture/network' },
        { text: 'نظام الطلب', link: '/ar/architecture/dialer' },
        { text: 'نظام الاستماع', link: '/ar/architecture/listener' },
        { text: 'الاستكشاف', link: '/ar/architecture/sniffing' },
      ],
    },
    {
      text: 'بروتوكولات الوكيل',
      collapsed: false,
      items: [
        { text: 'نظرة عامة', link: '/ar/protocols/overview' },
        { text: 'VLESS', link: '/ar/protocols/vless' },
        { text: 'VMess', link: '/ar/protocols/vmess' },
        { text: 'Trojan', link: '/ar/protocols/trojan' },
        { text: 'Shadowsocks', link: '/ar/protocols/shadowsocks' },
        { text: 'ShadowTLS', link: '/ar/protocols/shadowtls' },
        { text: 'Hysteria2', link: '/ar/protocols/hysteria2' },
        { text: 'TUIC', link: '/ar/protocols/tuic' },
        { text: 'AnyTLS', link: '/ar/protocols/anytls' },
        { text: 'NaiveProxy', link: '/ar/protocols/naive' },
        { text: 'WireGuard', link: '/ar/protocols/wireguard' },
        { text: 'SOCKS / HTTP / Mixed', link: '/ar/protocols/socks-http' },
        { text: 'Direct / Block / DNS', link: '/ar/protocols/direct-block-dns' },
        { text: 'Redirect / TProxy', link: '/ar/protocols/redirect-tproxy' },
        { text: 'TUN', link: '/ar/protocols/tun' },
        { text: 'مجموعات الصادر', link: '/ar/protocols/groups' },
        { text: 'SSH / Tor / Tailscale', link: '/ar/protocols/ssh-tor-tailscale' },
      ],
    },
    {
      text: 'طبقة النقل',
      collapsed: false,
      items: [
        { text: 'نظرة عامة', link: '/ar/transport/overview' },
        { text: 'طبقات نقل V2Ray', link: '/ar/transport/v2ray' },
        { text: 'WebSocket', link: '/ar/transport/websocket' },
        { text: 'gRPC', link: '/ar/transport/grpc' },
        { text: 'HTTP / HTTPUpgrade', link: '/ar/transport/http' },
        { text: 'QUIC', link: '/ar/transport/quic' },
        { text: 'TLS / uTLS / REALITY', link: '/ar/transport/tls' },
        { text: 'kTLS', link: '/ar/transport/ktls' },
        { text: 'تعدد الإرسال (smux)', link: '/ar/transport/mux' },
        { text: 'UDP over TCP', link: '/ar/transport/uot' },
        { text: 'تجزئة TLS', link: '/ar/transport/tls-fragment' },
      ],
    },
    {
      text: 'نظام DNS',
      collapsed: false,
      items: [
        { text: 'نظرة عامة', link: '/ar/dns/overview' },
        { text: 'العميل والموجّه', link: '/ar/dns/client-router' },
        { text: 'أنواع النقل', link: '/ar/dns/transports' },
        { text: 'FakeIP', link: '/ar/dns/fakeip' },
        { text: 'Hosts والمحلي', link: '/ar/dns/hosts-local' },
        { text: 'التخزين المؤقت وEDNS0', link: '/ar/dns/caching' },
      ],
    },
    {
      text: 'ميزات متقدمة',
      collapsed: false,
      items: [
        { text: 'مجموعات القواعد (SRS)', link: '/ar/advanced/rule-sets' },
        { text: 'GeoIP / GeoSite', link: '/ar/advanced/geo' },
        { text: 'مطابقة العمليات', link: '/ar/advanced/process' },
        { text: 'Clash API', link: '/ar/advanced/clash-api' },
        { text: 'V2Ray API', link: '/ar/advanced/v2ray-api' },
        { text: 'ملف التخزين المؤقت', link: '/ar/advanced/cache' },
        { text: 'المنصة / libbox', link: '/ar/advanced/platform' },
      ],
    },
    {
      text: 'الإعدادات',
      collapsed: false,
      items: [
        { text: 'بنية الإعدادات', link: '/ar/config/structure' },
        { text: 'أنواع الخيارات', link: '/ar/config/types' },
        { text: 'علامات البناء', link: '/ar/config/build-tags' },
      ],
    },
    {
      text: 'التنفيذ',
      collapsed: false,
      items: [
        { text: 'قائمة المراجعة', link: '/ar/implementation/checklist' },
        { text: 'ملاحظات التوافق', link: '/ar/implementation/compatibility' },
      ],
    },
  ],
  '/ru/': [
    {
      text: 'Архитектура',
      collapsed: false,
      items: [
        { text: 'Обзор', link: '/ru/architecture/overview' },
        { text: 'Жизненный цикл Box', link: '/ru/architecture/lifecycle' },
        { text: 'Интерфейсы адаптеров', link: '/ru/architecture/adapters' },
        { text: 'Реестр сервисов', link: '/ru/architecture/service-registry' },
        { text: 'Маршрутизатор и правила', link: '/ru/architecture/router' },
        { text: 'Менеджер соединений', link: '/ru/architecture/connection' },
        { text: 'Сетевой менеджер', link: '/ru/architecture/network' },
        { text: 'Система Dialer', link: '/ru/architecture/dialer' },
        { text: 'Система Listener', link: '/ru/architecture/listener' },
        { text: 'Анализ протоколов', link: '/ru/architecture/sniffing' },
      ],
    },
    {
      text: 'Прокси-протоколы',
      collapsed: false,
      items: [
        { text: 'Обзор', link: '/ru/protocols/overview' },
        { text: 'VLESS', link: '/ru/protocols/vless' },
        { text: 'VMess', link: '/ru/protocols/vmess' },
        { text: 'Trojan', link: '/ru/protocols/trojan' },
        { text: 'Shadowsocks', link: '/ru/protocols/shadowsocks' },
        { text: 'ShadowTLS', link: '/ru/protocols/shadowtls' },
        { text: 'Hysteria2', link: '/ru/protocols/hysteria2' },
        { text: 'TUIC', link: '/ru/protocols/tuic' },
        { text: 'AnyTLS', link: '/ru/protocols/anytls' },
        { text: 'NaiveProxy', link: '/ru/protocols/naive' },
        { text: 'WireGuard', link: '/ru/protocols/wireguard' },
        { text: 'SOCKS / HTTP / Mixed', link: '/ru/protocols/socks-http' },
        { text: 'Direct / Block / DNS', link: '/ru/protocols/direct-block-dns' },
        { text: 'Redirect / TProxy', link: '/ru/protocols/redirect-tproxy' },
        { text: 'TUN', link: '/ru/protocols/tun' },
        { text: 'Группы исходящих', link: '/ru/protocols/groups' },
        { text: 'SSH / Tor / Tailscale', link: '/ru/protocols/ssh-tor-tailscale' },
      ],
    },
    {
      text: 'Транспортный уровень',
      collapsed: false,
      items: [
        { text: 'Обзор', link: '/ru/transport/overview' },
        { text: 'Транспорты V2Ray', link: '/ru/transport/v2ray' },
        { text: 'WebSocket', link: '/ru/transport/websocket' },
        { text: 'gRPC', link: '/ru/transport/grpc' },
        { text: 'HTTP / HTTPUpgrade', link: '/ru/transport/http' },
        { text: 'QUIC', link: '/ru/transport/quic' },
        { text: 'TLS / uTLS / REALITY', link: '/ru/transport/tls' },
        { text: 'kTLS', link: '/ru/transport/ktls' },
        { text: 'Мультиплексирование (smux)', link: '/ru/transport/mux' },
        { text: 'UDP over TCP', link: '/ru/transport/uot' },
        { text: 'Фрагментация TLS', link: '/ru/transport/tls-fragment' },
      ],
    },
    {
      text: 'Система DNS',
      collapsed: false,
      items: [
        { text: 'Обзор', link: '/ru/dns/overview' },
        { text: 'Клиент и маршрутизатор', link: '/ru/dns/client-router' },
        { text: 'Типы транспорта', link: '/ru/dns/transports' },
        { text: 'FakeIP', link: '/ru/dns/fakeip' },
        { text: 'Hosts и локальное разрешение', link: '/ru/dns/hosts-local' },
        { text: 'Кэширование и EDNS0', link: '/ru/dns/caching' },
      ],
    },
    {
      text: 'Расширенные функции',
      collapsed: false,
      items: [
        { text: 'Наборы правил (SRS)', link: '/ru/advanced/rule-sets' },
        { text: 'GeoIP / GeoSite', link: '/ru/advanced/geo' },
        { text: 'Сопоставление процессов', link: '/ru/advanced/process' },
        { text: 'Clash API', link: '/ru/advanced/clash-api' },
        { text: 'V2Ray API', link: '/ru/advanced/v2ray-api' },
        { text: 'Файл кэша', link: '/ru/advanced/cache' },
        { text: 'Платформа / libbox', link: '/ru/advanced/platform' },
      ],
    },
    {
      text: 'Конфигурация',
      collapsed: false,
      items: [
        { text: 'Структура конфигурации', link: '/ru/config/structure' },
        { text: 'Типы опций', link: '/ru/config/types' },
        { text: 'Теги сборки', link: '/ru/config/build-tags' },
      ],
    },
    {
      text: 'Реализация',
      collapsed: false,
      items: [
        { text: 'Контрольный список', link: '/ru/implementation/checklist' },
        { text: 'Замечания о совместимости', link: '/ru/implementation/compatibility' },
      ],
    },
  ],
}

export default defineConfig({
  title: 'sing-box Internals',
  description: 'Complete technical analysis of sing-box for reimplementation',
  head: [['link', { rel: 'icon', href: '/favicon.ico' }]],
  sitemap: { hostname: 'https://singbox-internals.hidandelion.com' },
  locales: {
    root: {
      label: 'English',
      lang: 'en',
    },
    'zh-CN': {
      label: '简体中文',
      lang: 'zh-CN',
      title: 'sing-box 内部原理',
      description: 'sing-box 完整技术分析，用于重新实现',
      themeConfig: {
        nav: [
          { text: '架构', link: '/zh-CN/architecture/overview' },
          { text: '代理协议', link: '/zh-CN/protocols/overview' },
          { text: '传输层', link: '/zh-CN/transport/overview' },
          { text: 'DNS', link: '/zh-CN/dns/overview' },
          { text: '实现', link: '/zh-CN/implementation/checklist' },
        ],
        sidebar: {
          '/zh-CN/': sidebars['/zh-CN/'],
        },
        outline: {
          label: '本页目录',
          level: [2, 3],
        },
        lastUpdated: {
          text: '最后更新于',
        },
        docFooter: {
          prev: '上一页',
          next: '下一页',
        },
        darkModeSwitchLabel: '外观',
        returnToTopLabel: '返回顶部',
        sidebarMenuLabel: '菜单',
        search: {
          provider: 'local',
          options: {
            translations: {
              button: {
                buttonText: '搜索文档',
                buttonAriaLabel: '搜索文档',
              },
              modal: {
                noResultsText: '无法找到相关结果',
                resetButtonTitle: '清除查询条件',
                footer: {
                  selectText: '选择',
                  navigateText: '切换',
                  closeText: '关闭',
                },
              },
            },
          },
        },
      },
    },
    ar: {
      label: 'العربية',
      lang: 'ar',
      dir: 'rtl',
      title: 'sing-box من الداخل',
      description: 'تحليل تقني شامل لـ sing-box لإعادة التنفيذ',
      themeConfig: {
        nav: [
          { text: 'المعمارية', link: '/ar/architecture/overview' },
          { text: 'البروتوكولات', link: '/ar/protocols/overview' },
          { text: 'النقل', link: '/ar/transport/overview' },
          { text: 'DNS', link: '/ar/dns/overview' },
          { text: 'التنفيذ', link: '/ar/implementation/checklist' },
        ],
        sidebar: {
          '/ar/': sidebars['/ar/'],
        },
        outline: {
          label: 'محتويات الصفحة',
          level: [2, 3],
        },
        lastUpdated: {
          text: 'آخر تحديث',
        },
        docFooter: {
          prev: 'السابق',
          next: 'التالي',
        },
        darkModeSwitchLabel: 'المظهر',
        returnToTopLabel: 'العودة للأعلى',
        sidebarMenuLabel: 'القائمة',
        search: {
          provider: 'local',
          options: {
            translations: {
              button: {
                buttonText: 'بحث',
                buttonAriaLabel: 'البحث في الوثائق',
              },
              modal: {
                noResultsText: 'لم يتم العثور على نتائج',
                resetButtonTitle: 'إعادة تعيين البحث',
                footer: {
                  selectText: 'اختيار',
                  navigateText: 'تنقل',
                  closeText: 'إغلاق',
                },
              },
            },
          },
        },
      },
    },
    ru: {
      label: 'Русский',
      lang: 'ru',
      title: 'sing-box — внутреннее устройство',
      description: 'Полный технический анализ sing-box для повторной реализации',
      themeConfig: {
        nav: [
          { text: 'Архитектура', link: '/ru/architecture/overview' },
          { text: 'Протоколы', link: '/ru/protocols/overview' },
          { text: 'Транспорт', link: '/ru/transport/overview' },
          { text: 'DNS', link: '/ru/dns/overview' },
          { text: 'Реализация', link: '/ru/implementation/checklist' },
        ],
        sidebar: {
          '/ru/': sidebars['/ru/'],
        },
        outline: {
          label: 'Содержание',
          level: [2, 3],
        },
        lastUpdated: {
          text: 'Последнее обновление',
        },
        docFooter: {
          prev: 'Назад',
          next: 'Далее',
        },
        darkModeSwitchLabel: 'Оформление',
        returnToTopLabel: 'Наверх',
        sidebarMenuLabel: 'Меню',
        search: {
          provider: 'local',
          options: {
            translations: {
              button: {
                buttonText: 'Поиск',
                buttonAriaLabel: 'Поиск по документации',
              },
              modal: {
                noResultsText: 'Ничего не найдено',
                resetButtonTitle: 'Сбросить поиск',
                footer: {
                  selectText: 'Выбрать',
                  navigateText: 'Перейти',
                  closeText: 'Закрыть',
                },
              },
            },
          },
        },
      },
    },
  },
  themeConfig: {
    nav: [
      { text: 'Architecture', link: '/architecture/overview' },
      { text: 'Protocols', link: '/protocols/overview' },
      { text: 'Transport', link: '/transport/overview' },
      { text: 'DNS', link: '/dns/overview' },
      { text: 'Implementation', link: '/implementation/checklist' },
    ],
    sidebar: {
      '/': sidebars['/'],
      '/zh-CN/': sidebars['/zh-CN/'],
      '/ar/': sidebars['/ar/'],
      '/ru/': sidebars['/ru/'],
    },
    search: {
      provider: 'local',
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/SagerNet/sing-box' },
    ],
    outline: {
      level: [2, 3],
    },
  },
  markdown: {
    lineNumbers: true,
  },
})
